"$schema" = 'https://starship.rs/config-schema.json'

right_format = '$time'

[character]
success_symbol = '[➜](bold #a6e3a1)'
error_symbol = '[➜](bold #f38ba8)'

[aws]
disabled = true

[gcloud]
disabled = true

[directory]
style = "bold #89b4fa"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "󰘬 "
style = "bold #cba6f7"

[git_status]
style = "bold #f9e2af"
conflicted = "[●](#f38ba8)"
ahead = "[⇡](#a6e3a1)"
behind = "[⇣](#fab387)"
diverged = "[⇕](#f9e2af)"
untracked = "[●](#cba6f7)"
stashed = "[●](#89dceb)"
modified = "[●](#f9e2af)"
staged = "[●](#a6e3a1)"
renamed = "[●](#89b4fa)"
deleted = "[●](#f38ba8)"

[nodejs]
symbol = "󰎙 "
style = "bold #a6e3a1"
format = "[$symbol($version )]($style)"

[rust]
symbol = "🦀 "
style = "bold #fab387"
format = "[$symbol($version )]($style)"

[python]
symbol = "󰌠 "
pyenv_version_name = true
style = "bold #f9e2af"
format = "[$symbol($virtualenv )$version]($style) "

[golang]
symbol = "🐹 "
style = "bold #89dceb"
format = "[$symbol($version )]($style)"

[java]
symbol = "☕ "
style = "bold #f38ba8"
format = "[$symbol($version )]($style)"

[php]
symbol = "🐘 "
style = "bold #cba6f7"
format = "[$symbol($version )]($style)"

[dart]
symbol = "🎯 "
style = "bold #89b4fa"
format = "[$symbol($version )]($style)"

[docker_context]
symbol = "🐳 "
style = "bold #89b4fa"
format = "[$symbol$context]($style) "

[kubernetes]
symbol = "⎈ "
format = 'on [$symbol$context( \($namespace\))](bold #89dceb) '
style = "bold #89dceb"
disabled = false
detect_extensions = []
detect_files = ['k8s', 'kube']
detect_folders = ['.kube']
detect_env_vars = ['KUBECONFIG', 'KUBECTL_CONTEXT']

[package]
disabled = true

[time]
disabled = false
format = '🕙[$time]($style)'
time_format = "%H:%M:%S"
style = "bold #bac2de"

[line_break]
disabled = false
